version: '3.8'

services:
  piotr:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: piotr
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@piotr.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json 
    depends_on:
      - piotr

 sentry-backend:
    image: sentry:latest
    ports:
      - "9000:9000"
    environment:
      - SENTRY_DSN=http://localhost:8080
      - SENTRY_ENVIRONMENT=production

  sentry-frontend:
    image: sentry:latest
    ports:
      - "9001:9001"
    command: sentry-cli deploy
    depends_on:
      - sentry-backend