GET http://localhost:8080/api/product/list

###

GET http://localhost:8080/api/product/1

###

POST http://localhost:8080/api/order
Content-Type: application/json

{
  "customer": {
    "firstName": "John",
    "lastName": "Smith",
    "email": "john_smith@gmail.com"
  },
  "deliveryOptionItemCode": "2_DAY_SHIPPING-SHIPPING",
  "billingOptionItemCode": "CART-PAYMENT",
  "created": "2023-04-08T14:23:36.481",
  "comment": "This is a test order.",
  "shippingAddress": {
    "street": "Main Street",
    "houseNumber": "123",
    "zipCode": "12345",
    "city": "New York",
    "country": "USA"
  },
  "billingAddress": {
    "street": "Quiet Street",
    "houseNumber": "456",
    "zipCode": "54321",
    "city": "New York",
    "country": "USA"
  },
  "cart": {
    "freeShipping": true,
    "itemCount": 2,
    "cartPrice": 109.98,
    "lines": [
      {
        "productId": 1,
        "amount": 1,
        "lineTotal": 19.99
      },
      {
        "productId": 3,
        "amount": 1,
        "lineTotal": 89.99
      }
    ] 
  }
}

###

GET http://localhost:8080/api/order/list

###

GET http://localhost:8080/api/order/3