server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/piotr
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.api.piotr: DEBUG